config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bookmarks#index'
  
  resources :bookmarks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :site

  validates :title, presence: true, length: { minimum: 2 }
  validates :url, presence: true, format: { with: /(http:\/\/|https:\/\/)?(www.)?([a-zA-Z0-9]+).[a-zA-Z0-9]*.[a-z]{3}.?([a-z]+)?/, message: "must be a valid URL" }
  validates :shortening, length: { maximum: 10 }

  def top_level_url
    URI.parse(self.url).host
  end

  before_validation do
    self.site = Site.first_or_initialize({url: self.top_level_url})
  end

end

app/models/site.rb
class Site < ApplicationRecord
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def index
    if params[:search]
      condition = [:title, :url, :shortening].map { |e| e.to_s + ' ilike :search' }.join(' or ')
      @bookmarks = Bookmark.where(condition, {search: '%'+params[:search]+'%'})
    else
      @bookmarks = Bookmark.all
    end
  end

  def show
    @bookmark = Bookmark.find(params[:id])
  end

  def new
    @bookmark = Bookmark.new
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)

    if @bookmark.save
      redirect_to @bookmark
    else
      render 'new'
    end
  end

  def update
    @bookmark = Bookmark.find(params[:id])

    if @bookmark.update(bookmark_params)
      redirect_to @bookmark
    else
      render 'edit'
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to bookmarks_path
  end

  private

    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :shortening)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_form.html.erb
<%= form_for @bookmark, :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group <% if @bookmark.errors[:title].any? %> has-error <% end %>">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
      <% if @bookmark.errors[:title].any? %>
        <span id="helpBlock" class="help-block"><%= @bookmark.errors[:title].join(', ') %></span>
      <% end %>
    </div>
  </div>
  <div class="form-group <% if @bookmark.errors[:url].any? %> has-error <% end %>">
    <%= f.label :url, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :url, class: 'form-control' %>
      <% if @bookmark.errors[:url].any? %>
        <span id="helpBlock" class="help-block"><%= @bookmark.errors[:url].join(', ') %></span>
      <% end %>
    </div>
  </div>
  <div class="form-group <% if @bookmark.errors[:shortening].any? %> has-error <% end %>">
    <%= f.label :shortening, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :shortening, class: 'form-control' %>
      <% if @bookmark.errors[:shortening].any? %>
        <span id="helpBlock" class="help-block"><%= @bookmark.errors[:shortening].join(', ') %></span>
      <% end %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back', bookmarks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Edit Bookmark <em>"<%= @bookmark.title %>"</em></h1>

<%= render 'form' %>

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Site</th>
      <th>Url</th>
      <th>Shortening</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><b><%= bookmark.title %></b></td>
        <td><%= bookmark.site.url %></td>
        <td><%= bookmark.url %></td>
        <td><%= bookmark.shortening %></td>
        <td class="text-right">
          <%= link_to bookmark_path(bookmark), class: 'btn btn-default  btn-link ' do %>
            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            Show
          <% end %>
          <%= link_to edit_bookmark_path(bookmark), class: 'btn btn-primary  btn-link ' do %>
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            Edit
          <% end %>
          <%= link_to bookmark_path(bookmark), class: 'btn btn-danger  btn-link ', method: :delete, data: { confirm: 'Are you sure?' } do %>
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
            Remove
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookmarks/new.html.erb
<h1>Create Bookmark</h1>

<%= render 'form' %>

app/views/bookmarks/show.html.erb
<h1>Bookmark <em>"<%= @bookmark.title %>"</em></h1>

<%= form_for @bookmark, :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :title, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @bookmark.title %></p>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @bookmark.url %></p>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :shortening, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @bookmark.shortening %></p>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :site, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @bookmark.site.url %></p>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= link_to edit_bookmark_path(@bookmark), class: 'btn btn-primary' do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Edit
      <% end %>
      <%= link_to 'Back', bookmarks_path, class: 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="row margin-50">
        <div class="col-xs-6">
          <ul class="nav nav-pills">
            <li role="presentation" <% if current_page?(bookmarks_path) || current_page?(root_path) %> class="active" <% end %>>
              <%= link_to bookmarks_path do %>
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                Bookmarks
              <% end %>
            </li>
            <li role="presentation" <% if current_page?(new_bookmark_path) %> class="active" <% end %>>
              <%= link_to new_bookmark_path do %>
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                Create Bookmark
              <% end %>
            </li>
          </ul>
        </div>
        <div class="col-xs-6">
          <%= form_tag(bookmarks_path, method: "get") do %>
            <div class="input-group">
              <%= text_field_tag(:search, params[:search], class: 'form-control', placeholder: 'name, url, shortening...') %>
              <span class="input-group-btn">
                <%= submit_tag("Search", class: 'btn btn-default') %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>Hello World</h2>
<p>
  The time is now: <%= Time.now %>
</p>